# Generated by Django 4.1.7 on 2023-03-21 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cloth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='URL')),
                ('description', models.CharField(max_length=300, verbose_name='Описание')),
                ('colour', models.CharField(max_length=100, verbose_name='Цвет')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('size', models.CharField(max_length=50, verbose_name='Размер')),
                ('city_from', models.CharField(max_length=200, verbose_name='Город производства')),
                ('brand', models.CharField(max_length=200, verbose_name='Бренд')),
                ('collection', models.CharField(max_length=200, verbose_name='Коллекция')),
                ('type', models.CharField(max_length=200, verbose_name='Тип')),
                ('sex', models.CharField(max_length=200, verbose_name='Пол')),
                ('style', models.CharField(max_length=200, verbose_name='Стиль')),
                ('photo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
            ],
        ),
    ]
