# Generated by Django 4.2 on 2023-04-13 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cloth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название бренда')),
                ('description', models.CharField(max_length=200, verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Произведено')),
                ('description', models.CharField(max_length=200, verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название коллекции')),
                ('description', models.CharField(max_length=200, verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='Colour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Цвета')),
            ],
        ),
        migrations.CreateModel(
            name='Sex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Пол')),
                ('description', models.CharField(max_length=200, verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название стиля')),
                ('description', models.CharField(max_length=200, verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название коллекции')),
                ('description', models.CharField(max_length=200, verbose_name='Описание')),
            ],
        ),
        migrations.AlterField(
            model_name='cloth',
            name='brand',
            field=models.ForeignKey(max_length=200, on_delete=django.db.models.deletion.PROTECT, to='cloth.brands', verbose_name='Бренд'),
        ),
        migrations.AlterField(
            model_name='cloth',
            name='city_from',
            field=models.ForeignKey(max_length=200, on_delete=django.db.models.deletion.PROTECT, to='cloth.city', verbose_name='Город производства'),
        ),
        migrations.AlterField(
            model_name='cloth',
            name='collection',
            field=models.ForeignKey(max_length=200, on_delete=django.db.models.deletion.PROTECT, to='cloth.collection', verbose_name='Коллекция'),
        ),
        migrations.AlterField(
            model_name='cloth',
            name='colour',
            field=models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.PROTECT, to='cloth.colour', verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='cloth',
            name='sex',
            field=models.ForeignKey(max_length=200, on_delete=django.db.models.deletion.PROTECT, to='cloth.sex', verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='cloth',
            name='style',
            field=models.ForeignKey(max_length=200, on_delete=django.db.models.deletion.PROTECT, to='cloth.style', verbose_name='Стиль'),
        ),
        migrations.AlterField(
            model_name='cloth',
            name='type',
            field=models.ForeignKey(max_length=200, on_delete=django.db.models.deletion.PROTECT, to='cloth.type', verbose_name='Тип'),
        ),
    ]
